POST http://192.168.2.241:5000/api/user/create HTTP/1.1
content-type: application/json

{
    "username": "john"
}


###

POST http://127.0.0.1:5000/ HTTP/1.1
content-type: application/json

{
    "username": "john"
}

###

POST http://192.168.2.241:5000/api/user/find HTTP/1.1
content-type: application/json

{
    "userId": "john@gmail.com"
}


###

POST http://192.168.2.241/api/room/create HTTP/1.1
content-type: application/json

{
    "roomName": "belajar",
    "member": 5
}