POST http://192.168.2.241:5000/api/user/create HTTP/1.1
content-type: application/json

{
    "username": "memento2",

}


###

POST http://192.168.2.241:5000/ HTTP/1.1
content-type: application/json

{
    "email": "",
    "password": ""
}

###

POST http://192.168.2.241:5000/api/user/find HTTP/1.1
content-type: application/json

{
    "userId": 1
}


###

POST http://192.168.2.241/api/room/create HTTP/1.1
content-type: application/json

{
    "roomName": "belajar",
    "member": 5
}